spring:
  application:
    name: BooksApp
  cache:
    type: redis
    redis:
      cache-null-values: true
      host: localhost
      port: 6379
#      password:
#      time-to-live: 60000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
#      properties:
#        hibernate:
#          cache:
#            use_second_level_cache: true
#            use_query_cache: true
#            region.factory_class: org.hibernate.cache.redis.hibernate52.SingletonRedisRegionFactory
#            redis:
#              expiration: 120
#              hostname: localhost
#              port: 6379
  datasource:
    url: jdbc:h2:mem:booksdb
    driver-class-name: org.h2.Driver
#    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:/1_schema.sql
      data-locations: classpath:/2_data.sql
# Swagger URL : http://localhost:8080/swagger-ui/index.html