spring:
  application:
    name: BooksApp
  cache:
    type: none # none, simple, redis
    redis:
      cache-null-values: true
      host: localhost
      port: 6379
      time-to-live: 30000 # Time-to-live in milliseconds (e.g., 60000 ms = 60 seconds)
#      password:
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:booksdb
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:/1_schema.sql
      data-locations: classpath:/2_data.sql
# Swagger URL : http://localhost:8080/swagger-ui/index.html